# Generated by Django 3.2 on 2021-05-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
